language: php
sudo: false

addons:
  apt:
    packages:
      - git

php:
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files

notifications:
  email: false

env:
  global:
    - COMPOSER_OPTIONS="--no-suggest --no-interaction"
    - COMPOSER_PROCESS_TIMEOUT=0
  matrix:
    - CONFIG=rector.yml ANALYZE=".drupal/web/core/modules/node"
install:
  - echo -en "max_execution_time = 0\nxdebug.default_enable = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Speed up Drupal core installation.
  - composer global require hirak/prestissimo:^0.3.7 zaporylie/composer-drupal-optimizations:^1.1
  - composer install
  - composer download-drupal-core

script:
  - set -e
  - ./vendor/bin/rector process -c .travis/$CONFIG $ANALYZE --dry-run
